source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'BDBOAuth1Manager', '~> 1.5.0'

